-- =============================================
-- QUERIES DE CARGA A TABLAS DESTINO
-- =============================================

-- Creación de tabla destino en esquema ANALYTICS
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMER_ORDERS_DETAILED (
    CUSTOMER_KEY NUMBER(38,0),
    CUSTOMER_NAME VARCHAR(25),
    MARKET_SEGMENT VARCHAR(10),
    ORDER_DATE DATE,
    TOTAL_PRICE NUMBER(12,2),
    QUANTITY NUMBER(12,2),
    NET_PRICE NUMBER(12,2),
    CUSTOMER_SEGMENT VARCHAR(20),
    ORDER_SIZE_CATEGORY VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Inserción de datos transformados
INSERT INTO ANALYTICS.CUSTOMER_ORDERS_DETAILED (
    CUSTOMER_KEY,
    CUSTOMER_NAME,
    MARKET_SEGMENT, 
    ORDER_DATE,
    TOTAL_PRICE,
    QUANTITY,
    NET_PRICE,
    CUSTOMER_SEGMENT,
    ORDER_SIZE_CATEGORY
)
SELECT
    C_CUSTKEY,
    C_NAME,
    C_MKTSEGMENT,
    O_ORDERDATE,
    O_TOTALPRICE,
    L_QUANTITY,
    NET_PRICE,
    CUSTOMER_SEGMENT,
    ORDER_SIZE_CATEGORY
FROM business_metrics;
